// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestoManager_X.Models.RestosModel;

#nullable disable

namespace RestoManager_X.Migrations
{
    [DbContext(typeof(RestosDbContext))]
    [Migration("20250423214729_AddAvisEntity")]
    partial class AddAvisEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestoManager_X.Models.RestosModel.Avis", b =>
                {
                    b.Property<int>("CodeAvis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeAvis"));

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomPersonne")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.Property<int>("NumResto")
                        .HasColumnType("int");

                    b.HasKey("CodeAvis");

                    b.HasIndex("NumResto");

                    b.ToTable("TAvis", "resto", t =>
                        {
                            t.HasCheckConstraint("CK_Avis_Note", "[Note] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("RestoManager_X.Models.RestosModel.Proprietaire", b =>
                {
                    b.Property<int>("Numéro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numéro"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EmailProp");

                    b.Property<string>("Gsm")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("GsmProp");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NomProp");

                    b.HasKey("Numéro");

                    b.ToTable("TProprietaire", "resto");
                });

            modelBuilder.Entity("RestoManager_X.Models.RestosModel.Restaurant", b =>
                {
                    b.Property<int>("CodeResto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeResto"));

                    b.Property<string>("NomResto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Numprop")
                        .HasColumnType("int");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Tunisienne")
                        .HasColumnName("SpecResto");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("TelResto");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("VilleResto");

                    b.HasKey("CodeResto");

                    b.HasIndex("Numprop");

                    b.ToTable("TRestaurant", "resto");
                });

            modelBuilder.Entity("RestoManager_X.Models.RestosModel.Avis", b =>
                {
                    b.HasOne("RestoManager_X.Models.RestosModel.Restaurant", "LeResto")
                        .WithMany("LesAvis")
                        .HasForeignKey("NumResto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Relation_Resto_Avis");

                    b.Navigation("LeResto");
                });

            modelBuilder.Entity("RestoManager_X.Models.RestosModel.Restaurant", b =>
                {
                    b.HasOne("RestoManager_X.Models.RestosModel.Proprietaire", "Leroprietaire")
                        .WithMany("LesRestos")
                        .HasForeignKey("Numprop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Relation_Proprio_Restos");

                    b.Navigation("Leroprietaire");
                });

            modelBuilder.Entity("RestoManager_X.Models.RestosModel.Proprietaire", b =>
                {
                    b.Navigation("LesRestos");
                });

            modelBuilder.Entity("RestoManager_X.Models.RestosModel.Restaurant", b =>
                {
                    b.Navigation("LesAvis");
                });
#pragma warning restore 612, 618
        }
    }
}
