// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestoManager_X.Models.RestosModel;

#nullable disable

namespace RestoManager_X.Migrations
{
    [DbContext(typeof(RestosDbContext))]
    [Migration("20250419094843_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestoManager_X.Models.RestosModel.Proprietaire", b =>
                {
                    b.Property<int>("Numéro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numéro"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EmailProp");

                    b.Property<string>("Gsm")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("GsmProp");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NomProp");

                    b.HasKey("Numéro");

                    b.ToTable("TProprietaire", "resto");
                });

            modelBuilder.Entity("RestoManager_X.Models.RestosModel.Restaurant", b =>
                {
                    b.Property<int>("CodeResto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeResto"));

                    b.Property<string>("NomResto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Numprop")
                        .HasColumnType("int");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Tunisienne")
                        .HasColumnName("SpecResto");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("TelResto");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("VilleResto");

                    b.HasKey("CodeResto");

                    b.HasIndex("Numprop");

                    b.ToTable("TRestaurant", "resto");
                });

            modelBuilder.Entity("RestoManager_X.Models.RestosModel.Restaurant", b =>
                {
                    b.HasOne("RestoManager_X.Models.RestosModel.Proprietaire", "Leroprietaire")
                        .WithMany("LesRestos")
                        .HasForeignKey("Numprop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Relation_Proprio_Restos");

                    b.Navigation("Leroprietaire");
                });

            modelBuilder.Entity("RestoManager_X.Models.RestosModel.Proprietaire", b =>
                {
                    b.Navigation("LesRestos");
                });
#pragma warning restore 612, 618
        }
    }
}
